### ISSUE TITLE
Stackpane not autoscrolling

### ISSUE THREAD

**Issue by xCelestialPhoenix** [AY1920S2-CS2103T-F10-3/main#121]
The stackpane to display the output is not autoscrolling to the bottom after it exceeds the max height.

**Comment by huixianc** [comment]
can be fixed by adding `scrollPane.vvalueProperty().bind(resultDisplayPlaceholder.heightProperty());` to fillInnerParts() in MainWindow.java

**Comment by BryanYap972** [comment]
@xCelestialPhoenix  It has been fixed. My apologies
